<h1 align="center">Programación &#8212; PRE2013A45</h1>
<h3 align="center">Docente: Andrés Quintero Zea, PhD.</h3>
<h3 align="center">e-mail: andres.quintero27@eia.edu.co</h3>
<h3 align="center">Semana 11: Ecosistema Python - Numpy</h3>

`NumPy` (*Numerical Python*) es uno de los `módulos` más importantes y probablemente el más utilizado en el campo del cálculo numérico en el ecosistema de `Python`. 

- Ofrece el objeto `ndarray`, similar a una lista de `Python` pero optimizada para el cálculo numérico. Nos referiremos a este objeto como `array` de `NumPy`, o simplemente `array`.
- Implementa funciones matemáticas que pueden trabajar directamente sobre `arrays` sin tener que implementar ciclos.
- Proporciona funciones para leer/escribir datos a archivos de manera optimizada.
- Permite aplicaciones de álgebra lineal, generación de números aleatorios y transformadas de Fourier.

El núcleo de `Numpy` está implementado en C, ofreciendo *bindings* en `Python` para interactuar con él. Esto se traduce en que `NumPy` es más rápido que el equivalente en puro `Python`. Muchas otras librerías para el análisis de datos están construidas sobre `NumPy`, utilizando los `ndarrays` como la estructura de datos básica debido a su eficiencia.

In [6]:
import numpy as np
np.__version__

# 1. Fundamentos de los arreglos `NumPy`
La manipulación de datos en `Python` es casi sinónimo de la manipulación de arreglos `NumPy`. A continuación veremos varios ejemplos del uso de la manipulación de arreglos `NumPy` para acceder a datos y subarreglos. Y para dividir, reestructurar y unir los arreglos.

## 1.1 Atributos de arreglos `Numpy`
Primero analicemos algunos atributos útiles. Comenzaremos definiendo tres arreglos aleatorias, una matriz unidimensional, bidimensional y tridimensional. Usaremos el generador de números aleatorios de `NumPy`, que inicializaremos con un valor establecido para garantizar que se generen las mismas matrices aleatorias cada vez que se ejecute este código:

In [58]:
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5)) 

Cada matriz tiene atributos `ndim` (el número de dimensiones), `shape` (el tamaño de cada dimensión) y `size` (el tamaño total de la matriz):

In [12]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


Otro atributo útil es el `dtype`, el tipo de datos de la matriz.

In [13]:
print("dtype:", x3.dtype)

dtype: int32


Otros atributos incluyen `itemsize`, que enumera el tamaño (en bytes) de cada elemento de la matriz, y `nbytes`, que enumera el tamaño total (en bytes) de la matriz:

In [14]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 240 bytes


## 1.2 Indexación de arreglos `Numpy`
Ya estamos familiarizados con la indexación de listas estándar de `Python`, por lo que la indexación en `NumPy` nos resultará bastante familiar. En una matriz unidimensional, se puede acceder al $i$-ésimo valor (contando desde cero) especificando el índice deseado entre corchetes, al igual que con las listas de Python:

In [17]:
print(x1)
print(x1[0])
print(x1[-1])

[5 0 3 3 7 9]
5
9


In [29]:
print(x2)
print(x2[0])
print(x2[-1])
print(x2[0][0])
print(x2[0][-1])
print(x2[-3][-2])

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
[12  5  2  4]
[1 6 7 7]
12
4
2


Los valores también se pueden modificar utilizando cualquiera de las notaciones de índice anteriores:

In [23]:
x2[0, 0] = 12
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


Tenga en cuenta que, a diferencia de las listas de `Python`, las matrices `NumPy` tienen un tipo fijo. Esto significa, por ejemplo, que si intenta insertar un valor de punto flotante en una matriz de enteros, el valor se truncará silenciosamente. **¡No se deje sorprender por este comportamiento!**

In [25]:
x1[0] = 3.14159
print(x1)

[3 0 3 3 7 9]


## 1.3 Acceso a subarreglos
Así como podemos usar corchetes para acceder a elementos individuales de la matriz, también podemos usarlos para acceder a subarreglos con la notación de división, marcada por el carácter de dos puntos (`:`). La sintaxis de corte de `NumPy` sigue la de la lista estándar de Python `x[start:stop:step]`.
### 1.3.1 Arreglos unidimensionales

In [42]:
y1 = np.arange(10)
print(f'y1 = {y1}')
print(f'y1[:5] = {y1[:5]}')
print(f'y1[::-1] = {y1[::-1]}')

y2 = np.arange(0, 20, 2)
print(f'\ny2 = {y2}')
print(f'y2[5:] = {y2[5:]}')

y3 = np.linspace(0, 1,  9)
print(f'\ny3 = {y3}')
print(f'y3[2:5] = {y3[2:5]}')

y1 = [0 1 2 3 4 5 6 7 8 9]
y1[:5] = [0 1 2 3 4]
y1[::-1] = [9 8 7 6 5 4 3 2 1 0]

y2 = [ 0  2  4  6  8 10 12 14 16 18]
y2[5:] = [10 12 14 16 18]

y3 = [0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]
y3[2:5] = [0.25  0.375 0.5  ]


### 1.3.2 Arreglos multidimensionales
Los cortes multidimensionales funcionan de la misma manera, con varios cortes separados por comas. Por ejemplo:

In [50]:
print(f'x2 =\n {x2}')
print(f'\nx2[:2, :3] =\n{x2[:2, :3]}')
print(f'\nx2[:3, ::2] =\n {x2[:3, ::2]}')

x2 =
 [[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]

x2[:2, :3] =
[[12  5  2]
 [ 7  6  8]]

x2[:3, ::2] =
 [[12  2]
 [ 7  8]
 [ 1  7]]


Una rutina comúnmente necesaria es acceder a filas o columnas individuales de una matriz. Esto se puede hacer combinando la indexación y el corte, utilizando un segmento vacío marcado con dos puntos (`:`):

In [52]:
print(f'x2[:, 0] = \n {x2[:, 0]}')  # Primera columna de x2
print(f'x2[0, ;] = \n {x2[0, :]}')  # Primera fila de x2

x2[:, 0] = 
 [12  7  1]
x2[0, ;] = 
 [12  5  2  4]


Una cosa importante, y extremadamente útil, que debe saber sobre los segmentos de matriz es que devuelven vistas en lugar de copias de los datos de la matriz. Esta es un área en la que el corte de matrices `NumPy` difiere del corte de listas de `Python`: en las listas, los cortes serán copias. Considere nuestra matriz bidimensional de antes:

In [59]:
print(f'x2 = \n {x2}')
x2_sub = x2[:2, :2]
print(f'\nx2_sub =\n {x2_sub}')

x2 = 
 [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]

x2_sub =
 [[3 5]
 [7 6]]

x2_sub =
 [[99  5]
 [ 7  6]]

x2 = 
 [[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


Ahora, si modificamos este subarreglo, **¡veremos que el arreglo original ha cambiado!**

In [61]:
x2_sub[0, 0] = 150
print(f'\nx2_sub =\n {x2_sub}')
print(f'\nx2 = \n {x2}')


x2_sub =
 [[150   5]
 [  7   6]]

x2 = 
 [[150   5   2   4]
 [  7   6   8   8]
 [  1   6   7   7]]


Este comportamiento predeterminado es bastante útil: significa que cuando trabajamos con grandes conjuntos de datos, podemos acceder y procesar partes de estos conjuntos de datos sin necesidad de copiar el búfer de datos subyacente. Pero si queremos crear una copia independiente, podemos usar el método `copy()` de los arreglos.

In [64]:
x2_sub_copy = x2[:2, :2].copy()
print(f'x2_sub_copy =\n {x2_sub_copy}')
x2_sub_copy[0, 0] = 42
print(f'\nx2_sub_copy =\n {x2_sub_copy}')
print(f'\nx2 = \n {x2}')

x2_sub_copy =
 [[150   5]
 [  7   6]]

x2_sub_copy =
 [[42  5]
 [ 7  6]]

x2 = 
 [[150   5   2   4]
 [  7   6   8   8]
 [  1   6   7   7]]


### 1.3.3 Reestructuración de arreglos
Otro tipo útil de operación es la reestructuración de matrices. Por ejemplo, si desea poner los números del 1 al 9 en una matriz $3 \times 3$, puede hacer lo siguiente:

In [65]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Tenga en cuenta que para que esto funcione, el tamaño de la matriz inicial debe coincidir con el tamaño de la matriz reestructurada. Siempre que sea posible, el método de reestructuración utilizará una vista sin copia de la matriz inicial, pero con búferes de memoria no contiguos, este no es siempre el caso.

Otro patrón de reestructuració común es la conversión de una matriz unidimensional en una matriz bidimensional de filas o columnas. Esto se puede hacer con el método `reshape()`, o más fácilmente usando la palabra clave `newaxis` dentro de una operación de división:

In [76]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [77]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [78]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

## 1.4 Concatenación y división de matrices
Todas las rutinas anteriores funcionaron en matrices individuales. También es posible combinar varios arreglos en uno y, a la inversa, dividir un solo arreglo en varios arreglos. Echaremos un vistazo a esas operaciones aquí.
### 1.4.1 Concatenación
La concatenación, o unión de dos matrices en `NumPy`, se logra principalmente mediante las rutinas `np.concatenate`, `np.vstack` y `np.hstack`. `np.concatenate` toma una tupla o lista de matrices como primer argumento, como podemos ver aquí:

In [79]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

También puede concatenar más de dos matrices a la vez y para matrices bidimensionales:

In [80]:
z = [99, 99, 99]
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [81]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [82]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

Para trabajar con arreglos de dimensiones mixtas, puede ser más claro usar las funciones `np.vstack` (apilado vertical) y `np.hstack` (apilado horizontal):

In [83]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [85]:
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

De manera similar, `np.dstack` apilará matrices a lo largo del tercer eje.

### 1.4.2 División
Lo opuesto a la concatenación es la división, que se implementa mediante las funciones `np.split`, `np.hsplit` y `np.vsplit`. Para cada uno de estos, podemos pasar una lista de índices que dan los puntos de división:

In [88]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


Observe que $N$ puntos de división conducen a $N + 1$ subarreglos. Las funciones relacionadas `np.hsplit` y `np.vsplit` son similares:

In [89]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [90]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [91]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


De manera similar, `np.dsplit` dividirá matrices a lo largo del tercer eje.

# 2. Cálculo en matrices `NumPy`: funciones universales
Hasta ahora, hemos discutido algunos de los aspectos básicos de `NumPy`; En las próximas secciones, profundizaremos en las razones por las que `NumPy` es tan importante en el mundo de la ciencia de datos de `Python`. Es decir, proporciona una interfaz fácil y flexible para el cálculo optimizado con matrices de datos.

El cálculo en matrices `NumPy` puede ser muy rápido o muy lento. La clave para hacerlo rápido es usar operaciones vectorizadas, generalmente implementadas a través de las funciones universales de `NumPy` (*UFuncs*). Esta sección motiva la necesidad de los *UFuncs* de `NumPy`, que se pueden usar para hacer que los cálculos repetidos en los elementos de la matriz sean mucho más eficientes. Luego presenta muchos de los *UFuncs* aritméticos más comunes y útiles disponibles en el paquete `NumPy`.
## 2.1 Fundamentos de *UFuncs*
Para muchos tipos de operaciones, `NumPy` proporciona una interfaz conveniente para este tipo de rutina compilada y tipificada estáticamente. Esto se conoce como operación vectorizada. Esto se puede lograr simplemente realizando una operación en la matriz, que luego se aplicará a cada elemento. Este enfoque vectorizado está diseñado para insertar el bucle en la capa compilada que subyace a `NumPy`, lo que lleva a una ejecución mucho más rápida.

Compare los resultados de las siguientes ejecuciones:

In [92]:
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

1.42 s ± 40.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [93]:
%timeit (1.0 / big_array)

2.51 ms ± 80.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Las operaciones vectorizadas en `NumPy` se implementan a través de *UFuncs*, cuyo objetivo principal es ejecutar rápidamente operaciones repetidas en valores en matrices `NumPy`. Las *UFuncs* son extremadamente flexibles: antes vimos una operación entre un escalar y una matriz, pero también podemos operar entre dos matrices:

In [95]:
x = np.arange(5)
print(f'x = {x}')
y = np.arange(1, 6)
print(f'y = {y}')
print(f'x/y = {x/y}')

x = [0 1 2 3 4]
y = [1 2 3 4 5]
x/y = [0.         0.5        0.66666667 0.75       0.8       ]


In [99]:
z = np.arange(9).reshape((3, 3))
print(f'z = \n{z}')
print(f'\n  2 ** z = \n{ 2 ** z}')

z = 
[[0 1 2]
 [3 4 5]
 [6 7 8]]

  2 ** z = 
[[  1   2   4]
 [  8  16  32]
 [ 64 128 256]]


## 2.2 Explorando las UFuncs de `NumPy`
Los UFuncs existen en dos versiones: unarias, que operan en una sola entrada y binarias, que operan en dos entradas. Veremos ejemplos de ambos tipos de funciones aquí.
### 2.2.1 Aritmética de matrices
Los UFuncs de `NumPy` se sienten muy naturales de usar porque hacen uso de los operadores aritméticos nativos de `Python`. Se pueden usar las sumas, restas, multiplicaciones y divisiones estándar:

In [102]:
x = np.arange(4)
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


Además, se pueden encadenar como se desee y se respeta el orden estándar de las operaciones:

In [103]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

Cada una de estas operaciones aritméticas son simplemente envoltorios convenientes alrededor de funciones específicas integradas en `NumPy`. Por ejemplo, el operador `+` es un envoltorio para la función `add()`:

In [104]:
np.add(x, 2)

array([2, 3, 4, 5])

La siguiente tabla enumera los operadores aritméticos implementados en `NumPy`:

| Operador	    | UFunc equivalente   |
|:-------------:|:--------------------|
|``+``          |``np.add``           |
|``-``          |``np.subtract``      |
|``-``          |``np.negative``      |
|``*``          |``np.multiply``      |
|``/``          |``np.divide``        |
|``//``         |``np.floor_divide``  |
|``**``         |``np.power``         |
|``%``          |``np.mod``           |


### 2.2.2 Funciones útiles
`Numpy` integra funciones útiles, como las trigonométricas, valor absoluto, signo, logaritmo, etc.
#### 2.2.2.1 Valor absoluto, signo y magnitud

In [111]:
x = np.array([-2, -1, 0, 1, 2])
print(np.abs(x))
print(np.sign(x))

[2 1 0 1 2]
[-1 -1  0  1  1]


In [105]:
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
np.abs(x)

array([5., 5., 2., 1.])

#### 2.2.2.2 Funciones trigonométricas
**`Numpy` trabaja sobre ángulos en radianes**

In [109]:
theta = np.linspace(0, np.pi, 3)
print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


Los valores se calculan dentro de la precisión de la máquina, por lo que los valores que deberían ser cero no siempre llegan exactamente a cero. Las funciones trigonométricas inversas también están disponibles:

In [110]:
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


Para trabajar ángulos en radianes, se puede usar el método `deg2rad()` o implementar una función lambda:

In [112]:
np.sin(np.deg2rad(90))

1.0

In [116]:
sind = lambda degrees: np.sin(np.deg2rad(degrees))
cosd = lambda degrees: np.cos(np.deg2rad(degrees))
print(sind(75))
print(cosd(45))

0.9659258262890683
0.7071067811865476


#### 2.2.2.3 Exponenciales y logaritmos
Otro tipo común de operación disponible en `NumPy` son las exponenciales:

In [117]:
x = [1, 2, 3]
print("x     =", x)
print("e^x   =", np.exp(x))
print("2^x   =", np.exp2(x))
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


También están disponibles los inversos de las exponenciales, los logaritmos. El `np.log` básico da el logaritmo **natural**, si prefiere calcular el logaritmo en base 2 o el logaritmo en base 10, también están disponibles:

In [118]:
x = [1, 2, 4, 10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


También hay algunas versiones especializadas que son útiles para mantener la precisión con una entrada muy pequeña:

### 2.2.3 Funciones especiales
`NumPy` tiene muchos más UFuncs disponibles, incluidas funciones trigonométricas hiperbólicas, aritmética bit a bit, operadores de comparación, conversiones de radianes a grados, redondeo y resto, y mucho más. Un vistazo a la [documentación de NumPy](https://numpy.org/doc/stable/reference/index.html) revela muchas funcionalidades interesantes.

Otra fuente excelente para UFuncs más especializados y oscuros es el submódulo scipy.special. Si desea calcular alguna función matemática oscura en sus datos, es probable que esté implementada en scipy.special. Hay demasiadas funciones para enumerarlas todas, pero el siguiente fragmento muestra un par que podría surgir en un contexto de estadísticas:

In [121]:
from scipy import special
x = [1, 5, 10]
print("gamma(x)     =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 2)   =", special.beta(x, 2))

gamma(x)     = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2)   = [0.5        0.03333333 0.00909091]


In [122]:
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x)  =", special.erf(x))
print("erfc(x) =", special.erfc(x))
print("erfinv(x) =", special.erfinv(x))

erf(x)  = [0.         0.32862676 0.67780119 0.84270079]
erfc(x) = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x) = [0.         0.27246271 0.73286908        inf]


### 2.2.4 Agregados
Para UFuuncs binarias, hay algunos agregados interesantes que se pueden calcular directamente desde el objeto. Por ejemplo, si nos gustaría reducir una matriz con una operación en particular, podemos usar el método `reduce` de cualquier UFunc. Una reducción aplica repetidamente una operación determinada a los elementos de una matriz hasta que solo queda un único resultado.

Por ejemplo, llamar a `reduce` en `add` devuelve la suma de todos los elementos en la matriz:

In [125]:
x = np.arange(1, 6)
np.add.reduce(x)

15

De manera similar, llamar a `reduce` en `multiply` da como resultado el producto de todos los elementos de la matriz:

In [126]:
np.multiply.reduce(x)

120

Si quisiéramos almacenar todos los resultados intermedios del cómputo, podemos usar `accumulate` en su lugar:

In [127]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [128]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

Tenga en cuenta que para estos casos particulares, existen funciones `NumPy` dedicadas para calcular los resultados (`np.sum`, `np.prod`, `np.cumsum`, `np.cumprod`).

# 3. Ordenamiento de arreglos
Hasta este punto, nos hemos preocupado principalmente por las herramientas para acceder y operar en datos de matriz con `NumPy`. Esta sección cubre algoritmos relacionados con ordenamiento de valores en matrices `NumPy`.
Aunque `Python` tiene funciones integradas de ordenamiento con listas, no las discutiremos aquí porque la función `np.sort` de `NumPy` resulta ser mucho más eficiente y útil para nuestros propósitos. Por defecto, `np.sort` usa un algoritmo *quicksort* $\mathcal{O}(n\log{}n)$, aunque también están disponibles *mergesort* y *heapsort*. Para la mayoría de las aplicaciones, la ordenación rápida predeterminada es más que suficiente.

Para devolver una versión ordenada de la matriz sin modificar la entrada, puede usar `np.sort`:

In [129]:
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

Una función relacionada es `np.argsort`, que en su lugar devuelve los índices de los elementos ordenados:

In [132]:
i = np.argsort(x)
print(i)

[1 0 3 2 4]


El primer elemento de este resultado da el índice del elemento más pequeño, el segundo valor da el índice del segundo más pequeño y así sucesivamente. Estos índices se pueden usar (a través de una indexación elegante) para construir la matriz ordenada si se desea:

In [133]:
x[i]

array([1, 2, 3, 4, 5])

## 3.1 Ordenamiento de filas y columnas
Una característica útil de los algoritmos de ordenamiento de `NumPy` es la capacidad de ordenar filas o columnas específicas de una matriz multidimensional utilizando el argumento `axis`. Por ejemplo:

In [139]:
rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4, 6))
print(X)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [140]:
np.sort(X, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [141]:
np.sort(X, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

Tenga en cuenta que esto trata cada fila o columna como una matriz independiente, y se perderá cualquier relación entre los valores de fila o columna.

# Mini _challenge_ 11

### Para todos los puntos de este Mini challenge debe hacer uso de métodos y funciones de `Numpy`.

1. Escriba un programa para generar un vector de $N$ números aleatorios a partir de una distribución normal estándar, usando una precisión de dos cifras decimales. Luego, estos números se deben poner sobre la diagonal de una matriz $N \times N$, cuyos elementos por fuera de esta son todos cero.

    Por ejemplo, si se generan $N = 4$ números:

    <tt>0.42, 1.81, 0.36, -0.41</tt>

    La matriz debe ser:
    
    $\begin{matrix} 0.42 & 0 & 0 & 0 \\
    0 & 1.81 & 0 & 0 \\
    0 & 0 & 0.36 & 0 \\
    0 & 0 & 0 & -0.41 \end{matrix}$

    &nbsp;
2. Escriba un programa para crear una matriz de $10\times 10$, en la que los elementos en los bordes sean iguales a un número especificado por el usuario y los interiores iguales a 0.

    Por ejemplo, si el número ingresado es 10, la salida bede ser
    
    <tt>
    [[ 10.  10.  10.  10.  10.  10.  10.  10.  10.  10.]<br>
     [ 10.  0.  0.  0.  0.  0.  0.  0.  0.  10.]<br>
     [ 10.  0.  0.  0.  0.  0.  0.  0.  0.  10.]<br>
     [ 10.  0.  0.  0.  0.  0.  0.  0.  0.  10.]<br>
     [ 10.  0.  0.  0.  0.  0.  0.  0.  0.  10.]<br>
     [ 10.  0.  0.  0.  0.  0.  0.  0.  0.  10.]<br>
     [ 10.  0.  0.  0.  0.  0.  0.  0.  0.  10.]<br>
     [ 10.  0.  0.  0.  0.  0.  0.  0.  0.  10.]<br>
     [ 10.  0.  0.  0.  0.  0.  0.  0.  0.  10.]<br>
     [ 10.  10.  10.  10.  10.  10.  10.  10.  10.  10.]]
    </tt>
    
    &nbsp;
3. Escriba un programa que calcule un promedio ponderado de 15 números. Para esto deberá crear dos arreglos, `valores` en el que se especifican los números a ponderar y `pesos` en el que se especifica la importancia de cada número. Tenga en cuenta que para el cáalculo, `pesos` debe estar normalizado, es decir, la suma de todos sus elementos es 1. Por ejemplo, si los valores a ponderar son notas, es decir, se desea calcular promedio crédito, `pesos` tiene la información de los créditos asociados a cada nota y se divide por el total de créditos. Un ejemplo, con solo tres valores, sería:

   `valores = [4, 5, 3]`
    
   `pesos = [2, 1, 2]`

    El valor de `pesos` final deberá ser:
        
    `pesos = [0.4, 0.2, 0.4]`
        
    Y el promedio ponderado será `3.8`
## Condiciones de entrega
Para este Mini *challenge* se debe hacer entrega, a través del aula digital, de un archivo IPYNB con las soluciones a los problemas y que cuente con lo siguiente:
- Un primer bloque en Markdown a manera de portada, con la siguiente información centrada:
    * Identificación del curso
    * Nombre del estudiante
    * Identificación del mini *challenge*
    * Fecha
- Presentación de cada ejercicio en celda Markdown
- Celdas ejecutables con los problemas desarrollados

<img src="Images/by_nc_sa.svg" style="float:left;width: 50px;"/> &nbsp; El material de este curso está bajo una licencia Creative Commons [Atribución-NoComercial-CompartirIgual 4.0 Internacional](LICENSE.MD) (CC BY-NC-SA 4.0)
Este *Notebook* está parcialmente basado en el material complementario del libro [Python Data Science Handbook](https://www.oreilly.com/library/view/python-data-science/9781491912126/) disponible en [GitHub](https://github.com/jakevdp/PythonDataScienceHandbook).